#+TITLE: Will My Patch Make It? And How Fast? Case Study on the Linux Kernel
#+DATE: 2013-05-19
#+SETUPFILE: ~/git.w/octopress/source/octopress.org
#+OCTO-MD_LAYOUT: post
#+OCTO-MD_CATEGORIES: research papers
#+OCTO-MD_ICON: 960227_750
#+OCTO-MD_PUBLISHED: true

Today Yujuan presented our paper [[../assets/pdfs/papers/dmg2013_msrPatch.pdf][Will My Patch Make It? And How Fast? Case Study on the Linux Kernel]] at [[http://2013.msrconf.org/][MSR 2013]]. Its full bibliographic entry is:


#+begin_quote
Yujuan Jiang, Bram Adams, and Daniel M. German /Will My Patch Make It?
And How Fast? Case Study on the Linux Kernel/, International
Working Conference of Mining Software Repositories, MSR'2013, pages
XX-YY. May 2013.
#+end_quote

{{{more}}}

The main objective of the paper is to try to determine what are the
characteristics that make a patch being accepted by the Linux
development team.

#+begin_quote
The Linux kernel follows an extremely distributed reviewing and
integration process supported by 130 developer mailing lists and a
hierarchy of dozens of Git repositories for version control. Since not
every patch can make it and of those that do, some patches require a
lot more reviewing and integration effort than others, developers,
reviewers and integrators need support for estimating which patches
are worthwhile to spend effort on and which ones do not stand a
chance. This paper cross-links and analyzes eight years of patch
reviews from the kernel mailing lists and committed patches from the
Git repository to understand which patches are accepted and how long
it takes those patches to get to the end user. We found that 33\% of
the patches makes it into a Linux release, and that most of them need
3 to 6 months for this. Furthermore, that patches developed by more
experienced developers are more easily accepted and faster reviewed
and integrated. Additionally, reviewing time is impacted by submission
time, the number of affected subsystems by the patch and the number of
requested reviewers.
#+end_quote

The main outcome is that experience plays one of the most important 
factors.

--dmg
 
